acara/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import Acara, daftarAcara

app_name = 'acara'

urlpatterns = [
	path('acara/', views.Acara, name='acara')
	path('acara/daftarAcara', views.daftarAcara, name='daftarAcara')
]

register/urls.py
from django.urls import path
from .views import signUp, login, validate, logout, PersonAPI

app_name = "registrasi"
urlpatterns = [
    path('signing+up/', signUp),
    path('authenticating/', login),
    path('validating/', validate),
    path('logout/', logout),
    path('api/', PersonAPI.as_view())
]

tkBasdatE5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # new

]

register/models.py
from django.db import models


# Create your models here.

voucher/forms.py
from django import forms
from .models import modelsVoucher

class formVoucher(forms.Form):
    nama = forms.CharField(label='Nama',
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan nama voucher'}))
    kategori = forms.CharField(label="Kategori",
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan kategori voucher'}))
    nilai_poin = forms.IntegerField(label='Nilai Poin',
                             widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan nilai poin'}))
    deskripsi = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan deskripsi voucher'}))
    jumlah = forms.IntegerField(label='Jumlah',
                                widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Masukkan jumlah voucher'}))

register/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from .utils import ConnectDB
import simplejson
import random
import requests


class PersonAPI(APIView):
    permission_classes = (IsAuthenticated,)
    authentication_classes = (TokenAuthentication,)

    def get(self, request):
        user = request.user
        with connection.cursor() as cursor:
            if (user.email == "ANGGOTA"):
                cursor.execute(
                    "SELECT * FROM person p, anggota a WHERE p.ktp = a.ktp AND p.ktp = %s", [user.username])
                return Response(ConnectDB.dictfetchall(cursor))
            elif (user.email == "PETUGAS"):
                cursor.execute(
                    "SELECT * FROM person p, petugas a WHERE p.ktp = a.ktp AND p.ktp = %s", [user.username])
                return Response(ConnectDB.dictfetchall(cursor))
            elif (user.email == "ADMIN"):
                cursor.execute(
                    "SELECT * FROM person p, admin a WHERE p.ktp = a.ktp AND p.ktp = %s", [user.username])
                return Response(ConnectDB.dictfetchall(cursor))
            else:
                return HttpResponse("Cannot define user type.")


def signUp(request):
    if (request.method == "POST"):
        ktp = request.POST.get('ktp', None)
        email = request.POST.get('email', None)
        nama = request.POST.get('nama', None)
        alamat = request.POST.get('alamat', None)
        tgl_lahir = request.POST.get('tgl_lahir', None)
        no_telp = request.POST.get('no_telp', None)
        role = request.POST.get('role', None)
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO person VALUES(%s, %s, %s, %s, %s, %s, %s)", [
                ktp, email, nama, alamat, tgl_lahir, no_telp, role])
            if (role == "ADMIN"):
                cursor.execute(
                    "INSERT INTO admin VALUES(%s)", [ktp])
            elif (role == "ANGGOTA"):
                id = random.randint(0, 100000)
                cursor.execute(
                    "INSERT INTO anggota VALUES(%s, 0, 0, %s)", [str(id) + ktp[:4], ktp])
            else:
                cursor.execute(
                    "INSERT INTO PETUGAS VALUES(%s, 30000)", [ktp])
        user = User.objects.create_user(
            username=ktp, email=role, password=email)
        Token.objects.create(user=user)
        return HttpResponse("SUCCESS 200")
    else:
        return HttpResponse("HTTP 204")


def login(request):
    if (request.method == "POST"):
        taken = False
        ktp = request.POST.get('ktp', False)
        email = request.POST.get('email', False)
        data = {}
        with connection.cursor() as cursor:
            try:
                cursor.execute(
                    "SELECT ktp, nama, email, role from person where ktp = %s AND email = %s", [ktp, email])
                person = ConnectDB.dictfetchall(cursor)[0]
                token = requests.post(
                    ConnectDB.BASE_URL + '/auth/', {'username': person['ktp'], 'password': person['email']}).json()
                request.session['token'] = token['token']
                taken = True
            except:
                taken = False
            finally:
                data['is_taken'] = taken
                return JsonResponse(data)
    else:
        return HttpResponse("HTTP 204")


def validate(request):
    if (request.method == "POST"):
        ktp = request.POST.get('ktp', False)
        email = request.POST.get('email', False)
        data = {}
        with connection.cursor() as cursor:
            error = ""
            taken = False
            if (ktp != "" and email != ""):
                cursor.execute(
                    "SELECT ktp, nama, role from person where ktp = %s", [ktp])
                person = cursor.fetchone()
                if (person is not None):
                    error = "Ktp sudah terpakai"
                    taken = True
                cursor.execute(
                    "SELECT ktp, nama, role from person where email = %s", [email])
                person = cursor.fetchone()
                if (person is not None):
                    error = "Email sudah terpakai"
                    taken = True
            elif (ktp != ""):
                cursor.execute(
                    "SELECT ktp, nama, role from person where ktp = %s", [ktp])
                person = cursor.fetchone()
                if (person is not None):
                    error = "Ktp sudah terpakai"
                    taken = True
            elif (email != ""):
                cursor.execute(
                    "SELECT ktp, nama, role from person where email = %s", [email])
                person = cursor.fetchone()
                if (person is not None):
                    error = "Email sudah terpakai"
                    taken = True
            data = {
                'is_taken': taken,
                'error': error
            }
            return JsonResponse(data)
    else:
        return HttpResponse("HTTP 204")


def logout(request):
    request.session.flush()
    return HttpResponseRedirect("/")

register/templates/login.html
<h1 id="signin-title" hidden>Login</h1>
<form role="form" id="signin" hidden>
  <div class="form-group"><label for="id_ktp_login">No
      KTP</label><input type="text" class="form-control" id="id_ktp_login" placeholder="your id card..." /></div>
  <div class="form-group"><label for="id_email_login">Email
      address</label><input type="email" class="form-control" id="id_email_login" placeholder="your email..." /></div>
  <button id="login" type="submit" class="btn green m-1">Sign
    in</button>
  <p>Don't Have Account ? <a id="signup-in-trans">Sign up now.</a>
  </p>
</form>

register/templates/registrasi.html
<h1 id="signup-title" hidden>Signup</h1>
<form id="signup" method="POST" role="form" hidden>
  {% csrf_token %}
  <div class="form-group"><label for="id_ktp">No KTP</label>
    <div id="check-ktp" class="lds-ripple">
      <input type="text" class="form-control" id="id_ktp" name="ktp" placeholder="your id card..." />
      <div id="loading-ktp" class="sk-circle">
      </div>
    </div>
  </div>
  <div class="form-group"><label for="id_nama">Nama
      Lengkap</label><input type="name" class="form-control" id="id_nama" name="nama" placeholder="your name..." />
  </div>
  <div class="form-group"><label for="id_email">Email
      address</label>
    <div id="check-email" class="lds-ripple">
      <input type="email" class="form-control" id="id_email" name="email" placeholder="your email..." />
      <div id="loading-email" class="sk-circle"></div>
    </div>
  </div>
  <div class="form-group"><label for="id_tgl_lahir">Tanggal Lahir
      address</label><input type="date" class="form-control" id="id_tgl_lahir" name="tgl_lahir"
      placeholder="your phone number" />
  </div>
  <div class="form-group"><label for="id_no_telp">No.
      Telepon</label><input type="text" class="form-control" id="id_no_telp" name="no_telp"
      placeholder="your phone number" /></div>
  <div class="form-group"><label for="id_alamat">Alamat</label><input type="text" class="form-control" id="id_alamat"
      name="alamat" placeholder="your address..." />
  </div>
  <select id="id_role" class="ui fluid dropdown">
    <option hidden value="">Role</option>
    <option value="ADMIN">ADMIN</option>
    <option value="ANGGOTA">ANGGOTA</option>
    <option value="PETUGAS">PETUGAS</option>
  </select>
  <button disabled id="submit" type="submit" class="btn green m-1">Sign
    up</button>
  <p>Already have account ? <a id="signin-trans">Sign in here.</a>
  </p>
</form>